version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  auth:
    build: ./backend/services/auth
    container_name: auth_service
    depends_on:
      - db
    expose:
      - "5001"

  products:
    build: ./backend/services/products
    container_name: products_service
    depends_on:
      - db
    expose:
      - "5002"

  orders:
    build: ./backend/services/orders
    container_name: orders_service
    depends_on:
      - db
    expose:
      - "5003"

  payments:
    build: ./backend/services/payments
    container_name: payments_service
    depends_on:
      - db
    expose:
      - "5004"

  shipping:
    build: ./backend/services/shipping
    container_name: shipping_service
    depends_on:
      - db
    expose:
      - "5005"

  reviews:
    build: ./backend/services/reviews
    container_name: reviews_service
    depends_on:
      - db
    expose:
      - "5006"

  api-gateway:
    image: nginx:latest
    container_name: api_gateway
    depends_on:
      - auth
      - products
      - orders
      - payments
      - shipping
      - reviews
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  pgadmin_data:
